services:
  ai-agent:
    image: node:18-slim
    working_dir: /workspace
    volumes:
      - ${WORKTREE_PATH:-./}:/workspace:rw
      - ${CONTEXT_PATH:-./.context}:/context:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - WORKSPACE=/workspace
      - ISSUE_NUMBER=${ISSUE_NUMBER:-}
      - TASK=${TASK:-}
      - TASK_MSG=${TASK_MSG:-}
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        
        # Update package list and install basic dependencies
        apt-get update
        apt-get install -y git curl python3 python3-pip
        
        # Verify Node.js version
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        
        # Change to workspace
        cd /workspace
        
        # Check if we have an issue number or task
        if [ -f "/context/issue-${ISSUE_NUMBER:-}.md" ]; then
          echo "Reading issue context..."
          TASK_MSG="Read /context/issue-${ISSUE_NUMBER:-}.md and implement the solution. Follow the workflow in CLAUDE.md."
        elif [ -n "${TASK:-}" ]; then
          TASK_MSG="${TASK:-}"
        else
          TASK_MSG="Read the context in /context/ and work on the task. Follow the workflow in CLAUDE.md."
        fi
        
        
        # Start Claude if API key is available
        if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
          echo "Starting Claude with task: $TASK_MSG"
          npx @anthropic-ai/claude-code -p "$TASK_MSG" || echo "Claude execution completed"
        else
          echo "Task: $TASK_MSG"
          echo "Note: ANTHROPIC_API_KEY not set - container is ready for manual work"
          bash
        fi
    stdin_open: true
    tty: true