[project]
name = "factory-floor"
revision = "1.0"

[profiles.default]
#pass

# Development profile - with defaults for local development
[profiles.development]
# OpenCode AI Assistant
OPENAI_API_KEY = { description = "OpenAI API key for GPT models and OpenCode", required = true }

# Exa MCP Server
EXA_API_KEY = { description = "Exa API key for search and research tools", required = true }

# Context7 MCP Server (optional)
CONTEXT7_API_KEY = { description = "Context7 API key for documentation MCP server", required = false }

# Production profile - stricter requirements
[profiles.production]
OPENAI_API_KEY = { description = "OpenAI API key", required = true }
EXA_API_KEY = { description = "Exa API key", required = true }
CONTEXT7_API_KEY = { description = "Context7 API key", required = true }

# CI profile - for continuous integration
[profiles.ci]
OPENAI_API_KEY = { description = "CI OpenAI API key", required = true }
EXA_API_KEY = { description = "CI Exa API key", required = true }
