[project]
name = "factory-floor"
revision = "1.0"

# Default profile - development environment
[profiles.default]
# OpenCode AI Assistant
OPENAI_API_KEY = { description = "OpenAI API key for GPT models and OpenCode", required = false }

# Exa MCP Server
EXA_API_KEY = { description = "Exa API key for search and research tools", required = false }

# Context7 MCP Server (optional)
CONTEXT7_API_KEY = { description = "Context7 API key for documentation MCP server", required = false }

# Development profile - with defaults for local development
[profiles.development]
# Can provide development-specific defaults if needed
# For example, a shared team development API key (not recommended for production)

# Production profile - stricter requirements
[profiles.production]
OPENAI_API_KEY = { description = "OpenAI API key", required = true }
EXA_API_KEY = { description = "Exa API key", required = true }
CONTEXT7_API_KEY = { description = "Context7 API key", required = true }

# CI profile - for continuous integration
[profiles.ci]
OPENAI_API_KEY = { description = "CI OpenAI API key", required = true }
EXA_API_KEY = { description = "CI Exa API key", required = true }
